
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usrlab01
 */
public class Game extends javax.swing.JFrame {

    static PlayerController p1;
    static PlayerController p2;
    static BallController ball;
    
    Thread pt1;
    Thread pt2;
    Thread ballt;
    
    public Game() {
        initComponents();
        p1 = new PlayerController(jButtonPlayer1, jPanelGame);
        p2 = new PlayerController(jButtonPlayer2, jPanelGame);
        ball = new BallController(jPanelGame, jButtonBall, jButtonPlayer1, jButtonPlayer2, jLabelScorePlayer1, jLabelScorePlayer2);
        
        pt1 = new Thread(p1);
        pt2 = new Thread(p2);
        ballt = new Thread(ball);

        jPanelGame.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGame = new javax.swing.JPanel();
        jButtonPlayer2 = new javax.swing.JButton();
        jButtonPlayer1 = new javax.swing.JButton();
        jButtonBall = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelPlayer1 = new javax.swing.JLabel();
        jLabelPlayer2 = new javax.swing.JLabel();
        jLabelScorePlayer1 = new javax.swing.JLabel();
        jLabelScorePlayer2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(775, 620));
        setMinimumSize(new java.awt.Dimension(770, 536));
        setPreferredSize(new java.awt.Dimension(775, 577));

        jPanelGame.setBackground(new java.awt.Color(51, 51, 51));
        jPanelGame.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelGame.setPreferredSize(new java.awt.Dimension(746, 430));
        jPanelGame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanelGameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanelGameKeyReleased(evt);
            }
        });

        jButtonPlayer2.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPlayer2.setFocusable(false);

        jButtonPlayer1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPlayer1.setFocusable(false);

        jButtonBall.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBall.setFocusable(false);
        jButtonBall.setMaximumSize(new java.awt.Dimension(33, 33));
        jButtonBall.setMinimumSize(new java.awt.Dimension(33, 33));
        jButtonBall.setPreferredSize(new java.awt.Dimension(33, 33));

        javax.swing.GroupLayout jPanelGameLayout = new javax.swing.GroupLayout(jPanelGame);
        jPanelGame.setLayout(jPanelGameLayout);
        jPanelGameLayout.setHorizontalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addGroup(jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelGameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jButtonBall, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );
        jPanelGameLayout.setVerticalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButtonBall, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jButtonPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabelPlayer1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPlayer1.setText("Player 1: ");

        jLabelPlayer2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPlayer2.setText(" :Player 2");

        jLabelScorePlayer1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelScorePlayer1.setText("0");

        jLabelScorePlayer2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelScorePlayer2.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelPlayer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelScorePlayer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelScorePlayer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPlayer2)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlayer1)
                    .addComponent(jLabelPlayer2)
                    .addComponent(jLabelScorePlayer1)
                    .addComponent(jLabelScorePlayer2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGame, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jPanelGameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelGameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP)
        {
           p1.setMoveUp(true);
           if (pt1.isAlive()) 
            {
                pt1.interrupt();
            }
            pt1 = new Thread(p1);
            pt1.start();
        }

        if (evt.getKeyCode() == KeyEvent.VK_DOWN){
           p1.setMoveDown(true);
           if (pt1.isAlive()) 
            {
                pt1.interrupt();
            }
            pt1 = new Thread(p1);
            pt1.start();
        }

        if (evt.getKeyCode() == KeyEvent.VK_W){
           p2.setMoveUp(true);
           if (pt2.isAlive()) 
            {
                pt2.interrupt();
            }
            pt2 = new Thread(p2);
            pt2.start();
        }

        if (evt.getKeyCode() == KeyEvent.VK_S){
           p2.setMoveDown(true);
           if (pt2.isAlive()) 
            {
                pt2.interrupt();
            }
            pt2 = new Thread(p2);
            pt2.start();
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_SPACE){
           if (!ballt.isAlive()) 
            {
                ballt = new Thread(ball);
                ballt.start();
            }
        }
    }//GEN-LAST:event_jPanelGameKeyPressed

    private void jPanelGameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelGameKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP){
            p1.setMoveUp(false);
            if (pt1.isAlive()) 
            {
                pt1.interrupt();
            }
         }

         if (evt.getKeyCode() == KeyEvent.VK_DOWN){
            p1.setMoveDown(false);
            if (pt1.isAlive()) 
            {
                pt1.interrupt();
            }
         }

         if (evt.getKeyCode() == KeyEvent.VK_W){
            p2.setMoveUp(false);
            if (pt2.isAlive()) 
            {
                pt2.interrupt();
            }
         }

         if (evt.getKeyCode() == KeyEvent.VK_S){
            p2.setMoveDown(false);
            if (pt2.isAlive()) 
            {
                pt2.interrupt();
            }
         }
    }//GEN-LAST:event_jPanelGameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBall;
    private javax.swing.JButton jButtonPlayer1;
    private javax.swing.JButton jButtonPlayer2;
    private javax.swing.JLabel jLabelPlayer1;
    private javax.swing.JLabel jLabelPlayer2;
    private javax.swing.JLabel jLabelScorePlayer1;
    private javax.swing.JLabel jLabelScorePlayer2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGame;
    // End of variables declaration//GEN-END:variables
}
